name: smart_health_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  http: ^1.2.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

  # Fitbit / chart / token storage
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0

  # Apple Health / Google Fit
  health: ^13.2.0
  permission_handler: ^11.3.1



  # Optional background sync (can be added later)
  #workmanager: 0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
